# Generated by Django 3.2.6 on 2022-03-24 07:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartureProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_ticket', models.PositiveSmallIntegerField(default=0, unique=True)),
                ('driver_category', models.CharField(choices=[(None, 'Категория'), ('БВ', 'БВ'), ('МВ', 'МВ'), ('ОБВ', 'ОБВ')], default='Категория не указана', max_length=30)),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Номер по расписанию',
                'verbose_name_plural': 'Номера по расписанию',
            },
        ),
        migrations.CreateModel(
            name='RouteOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Маршрут', max_length=20, verbose_name='Название маршрута')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_shift', models.PositiveSmallIntegerField(default=0, unique=True)),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('is_full', models.BooleanField(default=False, verbose_name='Заполнение')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
            },
        ),
        migrations.CreateModel(
            name='TimeDeparture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_time', models.TimeField(null=True)),
                ('secondary_time', models.TimeField(null=True)),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Время по расписанию',
                'verbose_name_plural': 'Время по расписанию',
            },
        ),
        migrations.CreateModel(
            name='TripTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_ticket', models.PositiveSmallIntegerField(default=0, unique=True)),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Путевой лист',
                'verbose_name_plural': 'Путевые листы',
                'ordering': ['num_ticket'],
            },
        ),
        migrations.CreateModel(
            name='RouteNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_route', models.PositiveSmallIntegerField(default=0, unique=True, validators=[django.core.validators.MaxLengthValidator(6)])),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('route_order', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.routeorder', verbose_name='Название маршрута')),
            ],
            options={
                'verbose_name': 'Номер маршрута',
                'verbose_name_plural': 'Номера маршрутов',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(db_index=True, max_length=50, verbose_name='Фамилия')),
                ('driver_category', models.CharField(choices=[(None, 'Категория'), ('БВ', 'БВ'), ('МВ', 'МВ'), ('ОБВ', 'ОБВ')], default='Категория не указана', max_length=30)),
                ('shift', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.shift', verbose_name='Название маршрута')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_category', models.CharField(choices=[(None, 'Категория'), ('БВ', 'БВ'), ('МВ', 'МВ'), ('ОБВ', 'ОБВ')], default='Категория не указана', max_length=30)),
                ('num_bus', models.PositiveSmallIntegerField(default=0, unique=True)),
                ('is_fixed', models.BooleanField(default=False, verbose_name='Заполнение')),
                ('route_number', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.routenumber', verbose_name='Название маршрута')),
            ],
            options={
                'verbose_name': 'Автобус',
                'verbose_name_plural': 'Автобусы',
            },
        ),
    ]
