# Generated by Django 3.2.6 on 2022-03-24 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_category',
            field=models.CharField(choices=[(None, 'Категория'), ('БВ', 'БВ'), ('МВ', 'МВ'), ('ОБВ', 'ОБВ')], default='Категория не ', max_length=30),
        ),
        migrations.AlterField(
            model_name='routenumber',
            name='num_route',
            field=models.PositiveSmallIntegerField(default=0, unique=True, validators=[django.core.validators.MaxValueValidator(9999, 'Максимально допустимое значение номера маршрута 9999')], verbose_name='Номер маршрута'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='num_shift',
            field=models.PositiveSmallIntegerField(default=0, unique=True, verbose_name='Номер смены'),
        ),
    ]
