# Generated by Django 3.2.6 on 2022-03-23 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_busroutes_busroute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name': 'Автобус', 'verbose_name_plural': 'Автобусы'},
        ),
        migrations.AlterModelOptions(
            name='busroute',
            options={'verbose_name': 'Номер маршрута', 'verbose_name_plural': 'Номер маршрутов'},
        ),
        migrations.AlterModelOptions(
            name='departureprocess',
            options={'verbose_name': 'Номер по расписанию', 'verbose_name_plural': 'Номера по расписанию'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Водитель', 'verbose_name_plural': 'Водители'},
        ),
        migrations.AlterModelOptions(
            name='routeorder',
            options={'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршруты'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name': 'Смена', 'verbose_name_plural': 'Смены'},
        ),
        migrations.AlterModelOptions(
            name='timedeparture',
            options={'verbose_name': 'Время по расписанию', 'verbose_name_plural': 'Время по расписанию'},
        ),
        migrations.AlterModelOptions(
            name='tripticket',
            options={'verbose_name': 'Путевой лист', 'verbose_name_plural': 'Путевые листы'},
        ),
    ]
