# Generated by Django 3.2.6 on 2022-03-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220324_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bus_model',
            field=models.CharField(default='', max_length=50, verbose_name='Марка ТС'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_category',
            field=models.CharField(choices=[(None, 'Категория'), ('БВ', 'БВ'), ('МВ', 'МВ'), ('ОБВ', 'ОБВ')], max_length=30, verbose_name='Категория автобуса'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='is_fixed',
            field=models.BooleanField(default=False, verbose_name='Закреплен'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='num_bus',
            field=models.CharField(max_length=50, unique=True, verbose_name='Гос. номер ТС'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_category',
            field=models.CharField(choices=[(None, 'Категория'), ('БВ', 'БВ'), ('МВ', 'МВ'), ('ОБВ', 'ОБВ')], default='Категория', max_length=30, verbose_name='Категория водителя'),
        ),
        migrations.AlterField(
            model_name='routenumber',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменён'),
        ),
    ]
