# Generated by Django 3.2.6 on 2022-03-25 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220325_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routenumber',
            name='route_order',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.routeorder', verbose_name='Номер маршрута'),
        ),
        migrations.AlterField(
            model_name='routeorder',
            name='title',
            field=models.CharField(default='Маршрут', max_length=20, verbose_name='Номер маршрута'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='num_shift',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='Номер смены'),
        ),
    ]
