# Generated by Django 3.2.6 on 2022-03-25 08:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220325_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routenumber',
            name='route_order',
        ),
        migrations.AlterField(
            model_name='bus',
            name='route_number',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.routenumber', verbose_name='Номер маршрута'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.shift', verbose_name='Номер смены'),
        ),
        migrations.AlterField(
            model_name='routenumber',
            name='num_route',
            field=models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999, 'Максимально допустимое значение номера маршрута 9999')], verbose_name='Номер маршрута'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='num_shift',
            field=models.PositiveIntegerField(default=100, unique=True, verbose_name='Номер смены'),
        ),
    ]
