# Generated by Django 4.0.4 on 2022-04-12 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_bus_num_bus_alter_routenumber_num_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routenumber',
            name='num_route',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(limit_value=5, message='555')], verbose_name='Номер маршрута'),
        ),
    ]
